version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10

    working_directory: ~/react-sticky-box

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn is-prettier
      - run: yarn docz:build
  deploy-docs:
    docker:
      - image: circleci/node:10

    working_directory: ~/react-sticky-box

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn docz:deploy-from-ci

workflows:
  version: 2
  default:
    jobs:
      - build-and-test
      - deploy-docs:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
